alias ma='makeAlias'
alias ys='yarn start'
alias vbf='nvim ~/.bash_functions  && . ~/.bashrc'
alias mm='makeMacro'
alias vba='nvim ~/.bash_aliases && . ~/.bash_aliases'
alias ifl='installflow '
alias sl='serverless'
alias sx='startx'
alias pmh='cd ~/projects/patientme/homestead/'
alias vtm='nvim ~/.config/tmuxinator/dev.yml '
alias pml='cd ~/projects/patientme/core/machine-learning/'
alias li='lerna init'
alias cu='composer update'
alias pam='php artisan migrate'
alias killpostman='ps -aux | grep Postman | grep -v grep | tr -s " " | cut -d " " -f 2 | xargs kill'
alias ebd='eb deploy'
alias crna='create-react-native-app '
alias vc='nvim ~/.ctags'
alias pr='cd ~/projects'
alias clr='clear'
alias pf='cd projects/foreshadowme/'
alias nv='startEditing'
alias ep='expo publish'
alias ua='sudo pacman -S archlinux-keyring && sudo pacman -Syu'
alias va='vim ~/.bash_aliases '
alias gcl='git clone'
alias nig='ni -g'
alias sil='serverless invoke local --function'
alias si='serverless invoke --function'
alias sd='serverless deploy --aws-profile serverless'
alias airm='./agi3'
alias f='cd $(fd --type directory | fzf)'
alias seed='docker exec -it postgres find ./seeds/ -name "*sql" -type f -print0 | xargs -0 -I {} psql postgres://postgres:mysecretpassword@localhost:5432/postgres -a -f {}'
alias agi3='./agi3'
alias deb='docker ps | awk '\''{print $NF}'\'' | fzf | xargs -I% docker exec -it bash -c '\''docker exec -it % /bin/bash'\'''
alias pt='docker compose -f local.yml run django pytest'
alias tx='cat .env '
alias page='npx generate-react-cli component --type=page'
alias molecule='npx generate-react-cli component --type=molecule'
alias atom='npx generate-react-cli component --type=atom'
alias zp='zip -r agi3-prod.zip docker-compose.yml .envs'
alias 5120='xrandr --output HDMI-2 --mode 5120x1440'
alias 1920='xrandr --output HDMI-2 --mode 1920x1440'
alias 2560='xrandr --output HDMI-2 --mode 2560x1440'
alias bf="butterfish"

alias ac='agi3 checkout'
alias gp='git push'
alias ao='ac --open'
alias sp='docker compose -f local.yml run --rm django python manage.py shell_plus'
alias ollama='OLLAMA_HOST=0.0.0.0 ollama'
alias nvim-debug='nvim -V3nvim_debug.log'
alias ns='tmux new-session -A -s '
