local core = require("aniseed.core")
local nvim = require("aniseed.nvim")
local util = require("config.util")
nvim.o.relativenumber = false
nvim.o.signcolumn = "yes"
nvim.o.updatetime = 300
nvim.o.scrolloff = 999
nvim.o.exrc = true
nvim.o.shortmess = "a"
nvim.o.modelines = 0
nvim.o.pastetoggle = "<F5>"
nvim.o.tabstop = 4
nvim.o.shiftwidth = 4
nvim.o.softtabstop = 4
nvim.o.expandtab = true
nvim.o.cino = "f.5s"
nvim.o.undofile = true
return {["aniseed/module"] = "config.init"}